index:
  path:     /
  defaults: { _controller: 'general', _action: 'index' }
about:
  path:     /about
  defaults: { _controller: 'general', _action: 'about' }
contact:
  path:     /contact
  defaults: { _controller: 'general', _action: 'contact' }
backoffice-index:
  path:     /backoffice
  defaults: { _controller: 'auth', _action: 'index' }
backoffice-login:
  path:     /backoffice/login
  defaults: { _controller: 'auth', _action: 'login' }
backoffice-logout:
  path:     /backoffice/logout
  defaults: { _controller: 'auth', _action: 'logout' }
backoffice-welcome:
  path:     /backoffice/welcome
  defaults: { _controller: 'auth', _action: 'welcome' }
backoffice-page-list:
  path:     /backoffice/page/list
  defaults: { _controller: 'backoffice_page', _action: 'pageList' }
backoffice-page-edit:
  path:     /backoffice/page/{id}/edit
  defaults: { _controller: 'backoffice_page', _action: 'pageEdit' }
backoffice-page-delete:
  path:     /backoffice/page/{id}/delete
  defaults: { _controller: 'backoffice_page', _action: 'pageDelete' }
backoffice-console-list:
    path:     /backoffice/console/list
    defaults: { _controller: 'backoffice_console', _action: 'consoleList' }
backoffice-console-edit:
    path:     /backoffice/console/{id}/edit
    defaults: { _controller: 'backoffice_console', _action: 'consoleEdit' }
backoffice-console-delete:
    path:     /backoffice/console/{id}/delete
    defaults: { _controller: 'backoffice_console', _action: 'consoleDelete' }


